/* eslint-disable @typescript-eslint/no-var-requires */

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-08-09T13:00:24.623Z
 * Framework: nextjs
 * Output: src/
 */

import {
  createIgniterClient,
  useIgniterQueryClient,
} from '@igniter-js/core/client'
import type { AppRouterType } from './igniter.router'

/**
 * Type-safe API client generated from your Igniter router
 *
 * Usage in Server Components:
 * const users = await api.users.list.query()
 *
 * Usage in Client Components:
 * const { data } = api.users.list.useQuery()
 */
export const api = createIgniterClient<AppRouterType>({
  baseURL: process.env.NEXT_PUBLIC_IGNITER_APP_URL || 'http://localhost:3000',
  basePATH: process.env.NEXT_PUBLIC_IGNITER_APP_BASE_PATH || '/api/v1',
  router: () => {
    // Use the runtime router on both server and client to ensure all controllers
    // (including newly added ones like conversation) are available even if schema
    // is out of date.
    return require('./igniter.router').AppRouter
  },
})

/**
 * Type-safe API client generated from your Igniter router
 *
 * Usage in Server Components:
 * const users = await api.users.list.query()
 *
 * Usage in Client Components:
 * const { data } = api.users.list.useQuery()
 */
export type ApiClient = typeof api

/**
 * Type-safe query client generated from your Igniter router
 *
 * Usage in Client Components:
 * const { invalidate } = useQueryClient()
 */
export const useQueryClient = useIgniterQueryClient<AppRouterType>
